import React from "react";
import FirmHerose from "../../assets/FirmImage2.png"
import './FirmMaster.css'
const FirmMaster = () => {
 
  return (
    <div className='firm-content mt-2 voucher-content ' style={{ border: "3px double black", borderRadius: '5px', }}>
      <div className="container mt-2">
        <div className="container p-2 " >
          <div className="container justify-content-end align-items-end">
            <img src={FirmHerose} alt="firm-Herose" className="w-100 border border-danger-subtle rounded" height={"650px"} />
          </div>
        </div>
        <hr />
        <div className="Voucher-page container">
          <p className=" p-lg-5 justify-content-end ms-5 me-5 fs-5" >
          <b>
            <p>Firm Master -:  </p>
          </b>
            The <b>"Firm Master"</b> feature in accounting software serves as the foundational setup for any business or firm. It is a centralized repository where all essential details about the firm are stored, ensuring that every transaction and report generated by the software is accurate and relevant. This feature is crucial for the smooth operation of the accounting process, as it sets the context for all financial activities within the software.
            <br />
            <hr />
            <b className="fw-bold align-items-lg-start text-uppercase">Firm Master in Accounting Software:</b> <br />
            <ul>
              <li><b>Firm Name:</b> The name of the firm is the primary identifier and is used in all official documents and transactions. It should be entered accurately to ensure consistency across all records.
              </li>
              <li> <b>Address:</b> The registered address of the firm is crucial for legal and correspondence purposes. It includes details such as street address, city, state, and postal code.
              </li>
              <li><b>Contact Information:</b> This includes the firm's phone number, email address, and other contact details. Having up-to-date contact information is essential for communication with clients, suppliers, and regulatory bodies.
              </li>
              <li><b>Financial Year:</b> The financial year setup defines the start and end dates of the fiscal year. This is important for generating period-specific reports and for compliance with financial regulations.
              </li>
              <li><b>GSTIN (Goods and Services Tax Identification Number):</b> If applicable, the GSTIN must be entered. This is a unique identifier required for tax purposes, especially for businesses operating in regions where GST is applicable.
              </li>

              <li><b>PAN (Permanent Account Number):</b> The PAN is a unique identifier assigned to the firm by tax authorities. It is used for all tax-related activities and must be accurately recorded.</li>
              <li><b> Bank Details:</b>Bank account information, including the account number, bank name, branch, and IFSC code, is stored in the Firm Master. This facilitates smooth banking transactions and reconciliations.</li>

            </ul>
          </p>
        </div>
      </div>
    </div>
  );
};

export default FirmMaster;


