const SearcBarData = [
  //  Reckon Demo
  { "name": "Departmental Store [In Hindi]", "path": "departmental-store" },
  { "name": "Chemist Shop [In Hindi]", "path": "chemist-shop-software" },
  { "name": "Pharma Stockist [In Hindi]", "path": "pharm-stockist-software" },
  { "name": "Garments Footwear [In Hindi]", "path": "garment-sootwear-software" },
  { "name": "Mobile Electronics [In Hindi]", "path": "mobile-electronics-software" },
  { "name": "Pharma Distributor [In Hindi]", "path": "pharma-distributor-software" },
  { "name": "Restaurant Bar [In Hindi]", "path": "restaurant-bar-software" },
  // Installation
  { "name": "Download Reckon [For Installation]", "path": "download-reckon" },
  { "name": "DownloadSQLServer [For Installation", "path": "download-sql-server" },
  { "name": "Reckon Installation [For Installation]", "path": "reckon-installation" },
  { "name": "SQL Server Installation [For Instalation]", "path": "sql-server-installation" },
  { "name": "Update New Version [For Installation]", "path": "update-new-version[For Installation]" },
  { "name": "Download Control File [For Installation]", "path": "download-control-file" },
  { "name": "Download Print Format [For Installation]", "path": "download-print-formate" },
  { "name": "Create Firm DataBase [For Installation]", "path": "create-firm-database" },
  { "name": "Firm Detail Update [For Installation]", "path": "firm-detail-update" },
  { "name": "Invoice Formate Setup [For Installation]", "path": "invoice-formate-setup" },
  { "name": "E-Invoice Setup [For Installation]", "path": "e-invoice-setup" },
  { "name": "E-Way Bill Setup [For Installation]", "path": "e-way-bill-setup" },
  { "name": "E-mail Setup [For Installation]", "path": "email-setup" },
  { "name": "Import Mathod", "path": "import-mathod" },
  { "name": "WhatsApp Setup [Service]", "path": "whatsapp-setup" },
  { "name": "LAN Configure", "path": "lan-config" },
  { "name": "Auto Backup Setup", "path": "auto-backup-setup" },
  { "name": "User Create", "path": "user-create" },
  { "name": "Printer Page Setup", "path": "print-page-setup" },
  //Re Update Module
  { "name": "Re-Update Item Stock", "path": "re-update-item-stock" },
  { "name": "Re-Update Ledger Balance", "path": "re-update-ledger-balance" },
  { "name": "Master Rate Update", "path": "master-rate-update" },
  { "name": "Adjust Negative Stack", "path": "adjust-nagetive-stock" },
  { "name": "Re-Update Godown Stack", "path": "re-update-godwon-stock" },
  { "name": "Generate Production Entry", "path": "generation-production-entry" },
  // Administartion Start
  { "name": "Firm Master [In Hindi]", "path": "fm-ms" },
  { "name": "fy back up", "path": "fy-back-up" },
  { "name": "Return Home", "path": "home" },
  { "name": "Fy-Restore", "path": "fy-restore" },
  { "name": "Voucher Type", "path": "voucher-type" },
  { "name": "Sereis Master", "path": "series-master" },
  { "name": "User Module Entry", "path": "user-module-en" },
  { "name": "Global Use rEntry ", "path": "global-user-en" },
  { "name": "Global Update Rights Entry", "path": "gb-update-rt" },
  { "name": "User Series Rights Entry", "path": "user-srs-rth-en" },
  { "name": "User Firm Rights Entry", "path": "user-frm-rt-en" },
  { "name": "User Other Entry", "path": "user-other-en" },
  { "name": "Back Up Path Entry", "path": "backup-path-entry" },
  { "name": "Holiday Setup", "path": "holiday-path-en" },
  { "name": "Transfer Next Year", "path": "transfer-next-year" },
  { "name": "Favourite Menu Entry", "path": "fev-menu-en" },
  { "name": "Transfer Stock Ledger Balance", "path": "trans-stock-ledger-bal" },
  { "name": "Import Setting", "path": "import-setting" },
  { "name": "Re update", "path": "re-update" },
  // Start Utilitie
  { "name": "ReUpdate", "path": "re-update" },
  { "name": "Refresh Out Standing", "path": "refresh-out-standing" },
  { "name": "Data Export Telly [DE Telly ]", "path": "de-telly" },
  { "name": "DE Telly [Data Export Telly]", "path": "de-telly" },
  { "name": "DEReckon [Data Export Reckon]", "path": "de-reckon" },
  { "name": "Import Import Method", "path": "import-import-method" },
  { "name": "Import Reckon Voucher", "path": "import-reckon-voucher" },
  { "name": "Non Working Items Company", "path": "non-working-items-company" },
  { "name": "Non Working Ledger", "path": "non-working-ledger" },
  { "name": "Item Master Editing", "path": "item-master-editing" },
  { "name": "Multi Bill Print [Sale , Purchase]", "path": "multi-bill-print" },
  { "name": "Freez Sale Purchase", "path": "" },
  { "name": "Update HSN Code", "path": "update-hsn-code" },
  { "name": "Update GST Code", "path": "update-gst-code" },
  { "name": "Update GST Detail In Account", "path": "update-gst-in-detail-account" },
  { "name": "Multi Receipt Voucher Print", "path": "multi-receipt-voucher-print" },
  { "name": "Mark Transaction", "path": "mark-transaction" },
  { "name": "Un Mark Transaction", "path": "un-mark-transaction" },
  { "name": "Series Wise Format Entry", "path": "series-wise-format-entry" },
  { "name": "Bulk Company Email Entry", "path": "bulk-company-email.entry" },
  { "name": "Series Wise Party Wise Limit Entry", "path": "sereise-wise-party-wise-limit-entry" },
  // Start Merge Module
  { "name": "Merge Item Module", "path": "merge-item-module" },
  { "name": "Merge Ledger Module", "path": "merge-ledger-module" },
  { "name": "Merge Item", "path": "merge-item" },
  { "name": "Merge Batch", "path": "merge-batch" },
  { "name": "Merge Company", "path": "merge-company" },
  { "name": "Merge Item Group", "path": "merge-item-group" },
  { "name": "Merge Tax", "path": "merge-tax" },
  { "name": "Merge Salt", "path": "merge-salt" },
  { "name": "Merge Location", "path": "merge-location" },
  { "name": "Merge Other Group", "path": "merge-other-group" },
  { "name": "Merge Commodity Master", "path": "merge-commodity-master" },
  { "name": "Merge Schdule Master", "path": "merge-schdule-master" },
  { "name": "Merge Firm Balance", "path": "merge-firm-balance" },
  { "name": "Merge Ledger Master", "path": "merge-ledger-master" },
  { "name": "Merge Series", "path": "merge-series" },
  { "name": "Merge Area", "path": "merge-area" },
  { "name": "Merge Route", "path": "merge-route" },
  { "name": "Merge Station", "path": "merge-station" },
  { "name": "Merge Sales Man", "path": "merge-sales-man" },
  { "name": "Merge Delivery Man", "path": "merge-delivery-man" },
  { "name": "Merge Transporter", "path": "merge-transporter" },
  { "name": "Merge AcGroup", "path": "merge-acgroup" },
  { "name": "Merge City", "path": "merge-city" },
  { "name": "Merge State", "path": "merge-state" },
  { "name": "Merge Country", "path": "merge-country" },
  { "name": "Merge Bank", "path": "merge-bank" },
  { "name": "Mereg R Doctor", "path": "merge-r-doctor" },
  { "name": "Merge Patient", "path": "merge-patient" },
  // Account Master Star
  { "name": "Ledger Master", "path": "ledger-master" },
  { "name": "AccGroup", "path": "acc-group" },
  { "name": "Schedule", "path": "schedule" },
  { "name": "Ledger Opening Order", "path": "ledger-opening-order" },
  { "name": "Account Master Details Entry", "path": "account-maste-details-entry" },
  { "name": "Ledger Opening Master", "path": "ledger-opening-master" },
  { "name": "Approve Retailer Reckon Only", "path": "approve-retailer-reckonOnly" },
  // InventoryMaster
  { "name": "Item Master", "path": "item-master" },
  { "name": "Company Master", "path": "company-master" },
  { "name": "Store Godown", "path": "store-godwon" },
  { "name": "Salt Master", "path": "salt-master" },
  { "name": "Category Master", "path": "category-master" },
  { "name": "Schedule Master Entry", "path": "schedule-master-entry" },
  { "name": "Mfg Company Vs Supplier", "path": "mfgcompany-vs-supplier" },
  { "name": "Supplier Vs Mfg Company", "path": "supplier-vs-mfgcompany" },
  { "name": "Kit Master Entry", "path": "kit-master-entry" },
  { "name": "Stock Openig", "path": "stock-opening" },
  { "name": "Disc Comm Entry", "path": "disc-comm" },
  // Scheme Master
  { "name": "Scheme Master", "path": "schem-master" },
  { "name": "Promotional Offer Entry", "path": "promotion-offer-entry" },
  // Other Master
  { "name": "Location", "path": "location" },
  { "name": "State", "path": "state" },
  { "name": "City", "path": "city" },
  { "name": "Station", "path": "station" },
  { "name": "Route Other Master", "path": "route-other-master" },
  { "name": "Area", "path": "area" },
  { "name": "Transport", "path": "transport" },
  { "name": "Bank", "path": "bank" },
  { "name": "Narretion", "path": "narretion" },
  { "name": "Delivery Man", "path": "delivery-man" },
  { "name": "Mark Type Entry", "path": "mark-type-entry" },
  { "name": "Retail Order Entry", "path": "retail-order-entry" },
  { "name": "Item Purchase Order", "path": "item-p-o" },
  { "name": "Retail Order Vs Purchase", "path": "retail-order-vs-purchase" },
  // PriceDiscount
  { "name": "Price List", "path": "price-list" },
  { "name": "Party Wise Price List", "path": "party-wise-price-list" },
  { "name": "Import From Excel", "path": "import-from-excel" },
  { "name": "Series Wise Price List", "path": "series-Wise-Price-list" },
  // FieldForce
  { "name": "Sales Man", "path": "sales-man" },
  { "name": "Sales Manager", "path": "sales-manager" },
  { "name": "R Doctor Entry", "path": "r-doctor-entry" },
  { "name": "Zonal Sales Manager", "path": "zonal-sales-manager" },
  { "name": "Regional Sales Manager", "path": "regional-sales-manager" },
  { "name": "Area Sales Manager", "path": "area-sales-manager" },
  { "name": "Field Staff Area Entry", "path": "field-staff-area-entry" },
  { "name": "Field Staff Route Entry", "path": "field-staff-route-entry" },
  //  Loyalty Master
  { "name": "Loyalty Master Entry", "path": "loyalty-master-entry" },
  { "name": "Card Received Entry", "path": "card-received-entry" },
  { "name": "Card Recharge Entry", "path": "card-recharge-entry" },
  { "name": "Gift Voucher Entry", "path": "gift-voucher-entry" },
  // Account Master
  { "name": "All Ledger", "path": "all-ledger" },
  { "name": "Bank Reconcilation", "path": "bank-reconcilation" },
  { "name": "Cash Bank", "path": "cash-bank" },
  { "name": "Creditor Accounts", "path": "creditor-accounts" },
  { "name": "Debtor Accounts", "path": "debtor-accounts " },
  { "name": "Depriciation", "path": "depriciation" },
  { "name": "Duties Taxes", "path": "duties-taxes" },
  { "name": "Interest Calculation", "path": "interest-calculation" },
  { "name": "Ledger", "path": "ledger" },
  { "name": "Payment", "path": "payment" },
  { "name": "Purchase Summary", "path": "purchase-summary" },
  { "name": "Sale Summary", "path": "sale-summary" },
  { "name": "Bank Pay Slip Print", "path": "bank-pay-slip-print" },
  { "name": "Bank Receipt", "path": "bank-receipt" },
  { "name": "Cash Bank Receipt Entry", "path": "cash-Bank-receipt-entry" },
  { "name": "Cashier Entry", "path": "cashier-entry" },
  { "name": "Periodic Voucher Entry", "path": "periodic-voucher-entry" },
  { "name": "Cash Receipt", "path": "cash-receipt" },
  { "name": "Credit Bill Approving", "path": "credit-bill-approving" },
  { "name": "Multiple Voucher", "path": "multiple-voucher" },
  // Voucher Entry
  { "name": "Cheque Return Entry", "path": "cheque-return-entry" },
  { "name": "Contra Voucher", "path": "contra-voucher" },
  { "name": "Credit Note Voucher", "path": "credit-note-voucher" },
  { "name": "Debit Note Voucher", "path": "debit-note-voucher" },
  { "name": "Expense RCM Voucher", "path": "expense-rcm-voucher" },
  { "name": "Journal Voucher", "path": "journal-voucher" },
  { "name": "Payment Voucher", "path": "payment-voucher" },
  { "name": "Purchase Voucher", "path": "purchase-voucher" },
  { "name": "Receipt Voucher", "path": "receipt-voucher" },
  { "name": "Sale Voucher", "path": "sale-voucher" },
  { "name": "Show Voucher", "path": "show-voucher" },
  { "name": "Voucher Approving", "path": "voucher-approving" },
  { "name": "Self Voucher", "path": "self-voucher" },
  // Post Date Cheque
  { "name": "Pay In Slip", "path": "pay-in-slip" },
  { "name": "Pay In Slip Both", "path": "pay-in-slip-both" },
  { "name": "Pay In Slip Posted", "path": "pay-in-slip-posted" },
  { "name": "PDC Receipt", "path": "pdc-receipt" },
  { "name": "PDC Register Payment", "path": "pdc-register-payment" },
  { "name": "PDC Register Print", "path": "pdc-register-print" },
  { "name": "PDC Register Receipt", "path": "pdc-register-receipt" },
  { "name": "PDC Payment", "path": "pdc-payment" },
  // BooksOfAccount
  { "name": "Bank Book", "path": "bank-book" },
  { "name": "Cash Book", "path": "cash-book" },
  { "name": "Cash Book Tally", "path": "cash-book-tally" },
  { "name": "Contra Book", "path": "contra-book" },
  { "name": "Credit Note Book Voucher", "path": "creditNoteBook" },
  { "name": "Day Book", "path": "day-book" },
  { "name": "Debit Note Book Voucher", "path": "debitNoteBook" },
  { "name": "Item Day Book", "path": "item-day-book" },
  { "name": "Journal Book", "path": "journal-book" },
  { "name": "Payment Book", "path": "payment-book" },
  { "name": "Purchase Book Voucher", "path": "PurchaseBook" },
  { "name": "RCM Book", "path": "rcm-book" },
  { "name": "Receipt Book", "path": "receipt-book" },
  { "name": "Sale Book Voucher", "path": "SaleBook" },
  // Bank Reconcilation
  { "name": "Reconcilation Statement", "path": "ReconcilationStatement" },
  { "name": "Cheque Register Cleared", "path": "ChequeRegister" },
  { "name": "Cheque Register Un Cleared", "path": "ChequeRegister-UnCleared" },
  { "name": "Auto Bank Reckoncilation", "path": "AutoBankReckoncilation" },
  { "name": "Bank Reconcilation Entry", "path": "BankReconcilationEntry" },
  // Cheuqe Book 
  { "name": "Single Cheque Entry", "path": "single-cheque-entry" },
  { "name": "Cheque Book Register", "path": "cheque-book-register" },
  { "name": "Cheque Issuance Entry", "path": "cheque-issuance-entry" },
  { "name": "Cheque Received From Bank", "path": "cheque-Received-bank" },
  //OutStanding Report
  { "name": "Area Wise Ledger", "path": "area-wise-ledger" },
  { "name": "Bill Wise Tagging", "path": "bill-wise-tagging" },
  { "name": "OS Aging", "path": "os-aging" },
  { "name": "OS Area Wise", "path": "os-area-wise" },
  { "name": "OS Field Staff Wise", "path": "os-field-staff-wise" },
  { "name": "OS Mfg Company Wise", "path": "os-mfg-company-wise" },
  { "name": "OS Party Wise Print", "path": "os-party-wise-print" },
  { "name": "OS Route Wise", "path": "os-route-wise" },
  { "name": "OS Station Wise", "path": "os-station-wise" },
  { "name": "OS Supplier Wise", "path": "os-supplier-wise" },
  { "name": "Out standing Report", "path": "out-standing-report" },
  { "name": "Over Due List", "path": "over-due-list" },
  // Collection Report

  { "name": "Area Wise Sale Sale Return", "path": "area-wise-sale-sale-return" },
  { "name": "Collection All", "path": "collection-all" },
  { "name": "Collection Area Wise", "path": "collection-area-wise" },
  { "name": "Collection Field Staff Wise", "path": "collection-field-staff-wise" },
  { "name": "Collection Party Wise", "path": "collection-party-wise" },
  { "name": "Collection Report Comparision", "path": "collection-report" },
  { "name": "Collection Route Wise", "path": "collection-route-wise" },
  { "name": "Collection Station Wise", "path": "collection-station-wise" },
  { "name": "Inventory Field Staff Wise", "path": "inventory-field-staff-wise" },
  { "name": "Missing Receipt Number", "path": "missing-receipt-number" },
  // Online Banking
  { "name": "Payment Entry", "path": "payment-entry" },
  { "name": "Accounts On Line Bank Api Test", "path": "account-online-bank-api-test" },
  { "name": "Accounts On Line Bank Detail Entry", "path": "account-online-bank-detail-entry" },
  { "name": "Auto Bank Reconcilation Entry", "path": "auto-bank-reconcilation-entry" },
  { "name": "Bank Statement", "path": "bank-statment" },
  { "name": "Schedule Payment Entry", "path": "schedule-payment-entry" },
  // Sale Order 
  { "name": "Item SO", "path": "item-so" },
  { "name": "Item Wise Order Register", "path": "item-wise-order-register" },
  { "name": "On Line Sale Order Entry", "path": "on-line-sale-order-entry" },
  { "name": "Party SO", "path": "party-so" },
  { "name": "Pending SO", "path": "pending-so" },
  { "name": "Sale Order Register", "path": "sale-order-register" },
  { "name": "So Generation From Excel", "path": "" },
  // PurchaseOrder
  { "name": "On line Order Print", "path": "on-line-order-print" },
  { "name": "Party PO", "path": "party-po" },
  { "name": "Purchase Order", "path": "purchase-order" },
  { "name": "Purchase Order Register", "path": "purchase-order-register" },
  { "name": "Re Order System", "path": "re-order-system" },
  // Inventory Module
  { "name": "Expiry Issue", "path": "expiry-issue" },
  { "name": "Expiry Recieve", "path": "expiry-receive" },
  { "name": "Godwon Transfer", "path": "gowdown-transfer" },
  // Physical Stock, Stock Adjustment = stock-maintain shortcut url define
  { "name": "Physical Stock StockAdjustment", "path": "stock-maintain" },
  { "name": "Price Difference", "path": "price-difference" },
  { "name": "Purchase", "path": "purchase" },
  { "name": "Purchase Return", "path": "purchase-return" },
  { "name": "Replacement", "path": "replacemnt" },
  { "name": "Sale", "path": "sale" },
  { "name": "Sale Return", "path": "sale-return" },
  { "name": "Stock Transfer", "path": "stock-transfer" },
  // Sale Invoice
  { "name": "Bill History", "path": "bill-history" },
  { "name": "Bill Upload", "path": "bill-upload" },
  { "name": "Challan", "path": "challan" },
  { "name": "Challan Book", "path": "challan-book" },
  { "name": "Challan To Bill", "path": "challan-to-bill" },
  { "name": "Counter Book", "path": "counter-book" },
  { "name": "Counter Sale", "path": "counter-sale" },
  { "name": "Invoice", "path": "invoice" },
  { "name": "Retail Challan", "path": "retail-challan" },
  { "name": "Retail Sale", "path": "retail-sale" },
  { "name": "Sale Book", "path": "sale-book" },
  { "name": "Stock Issue", "path": "stock-issue" },
  { "name": "Stock Issue Book", "path": "stock-issue-book" },
  // Sale Retun Challan
  { "name": "Sale Return Book", "path": "sale-return-book" },
  { "name": "Sale Return Challan", "path": "sale-return-challan" },
  { "name": "Sale Return Challan Book", "path": "sale-return-challan-book" },
  { "name": "Sale Return Note", "path": "sale-return-note" },
  { "name": "Sale Return Retail", "path": "sale-return-retail" },
  // Sale Invoice
  { "name": "Sale Return Book", "path": "sale-return-book" },
  { "name": "Sale Return Challan", "path": "sale-return-challan" },
  { "name": "Sale Return Challan Book", "path": "sale-return-challan-book" },
  { "name": "Sale Return Note", "path": "sale-return-note" },
  { "name": "Sale Return Retail", "path": "sale-return-retail" },
  //Purchase Invoice
  { "name": "Import Purchase", "path": "import-purchase" },
  { "name": "Map Item List", "path": "map-item-list" },
  { "name": "Purchase Challan To Bill", "path": "p-challan-to-bill" },
  { "name": "Purchase Invoice", "path": "p-invoice" },
  { "name": "Purchase Book", "path": "purchase-book" },
  { "name": "Purchase Challan Book", "path": "purchase-challan-bill" },
  { "name": "Stock Recieve", "path": "stock-receive " },
  // Purchase Return
  { "name": "Purchase Return Book", "path": "purchase-return-book" },
  { "name": "Purchase Return Challan", "path": "purchase-return-challan" },
  { "name": "Purchase Return Challan Book", "path": "p-return-challan-book" },
  { "name": "Purchase Return Note", "path": "purchase-return-note" },
  // Replacement
  { "name": "Replacement Issue", "path": "replacement-issue" },
  { "name": "Replacement Issue Book", "path": "replacement-issue-book" },
  { "name": "Replacement Receive", "path": "replacement-receive" },
  { "name": "Replacement Receive Book", "path": "replacement-receive-book" },
  // Price Diference
  { "name": "P.P.Difference Note Book", "path": "p-price-difference-note" },
  { "name": "P.Price Difference Note", "path": "p-price-difference-note" },
  { "name": "Sale Price Difference Note", "path": "sale-price-difference-note" },
  { "name": "Sale Price Difference Note Book", "path": "sale-price-difference-note-book" },
  // Expiry Issue
  { "name": "Expiry Issue Book", "path": "expiry-issue-book" },
  { "name": "Expiry Issue Challan", "path": "expiry-issue-challan" },
  { "name": "Expiry Issue Challan Book", "path": "expiry-issue-challan-book" },
  { "name": "Expiry Issue Challan JV", "path": "expiry-issue-challan-jv" },
  { "name": "Expiry Issue Challan JV Print", "path": "expiry-issue-challan-jv-print" },
  { "name": "Expiry Issue Note", "path": "expiry-issue-note" },
  // Expiry Receive
  { "name": "Expiry Receive Challan", "path": "expiry-receive-challan" },
  { "name": "Expiry Challan JV", "path": "expiry-challan-jv" },
  { "name": "Expiry Challan JV Print", "path": "expiry-challan-jv-print" },
  { "name": "Expiry Receive Book", "path": "expiry-receive-book" },
  { "name": "Expiry Receive Challan Book", "path": "expiry-receive-challan-book" },
  { "name": "Expiry Receive Note", "path": "expiry-receive-note" },
  { "name": "Non Claim Exp In", "path": "non-claim-exp-in" },
  // Stock Transfer And Stock Report
  { "name": "Stock Status", "path": "stock status" },
  { "name": "Expiry Report", "path": "expiry-report" },
  { "name": "Stock Sales Statement", "path": "stock-&-sales-statment" },
  { "name": "Expiry Stock", "path": "expiry-stock" },
  { "name": "Near Expiry Stock", "path": "near-expiry-stock" },
  { "name": "Ban Stock", "path": "ban-stock" },
  { "name": "Minimum Level Stock", "path": "minimum-level-stock" },
  { "name": "Dump Stock", "path": "dump-stock" },
  { "name": "Hold Stock", "path": "hold-stock" },
  { "name": "Closing Stock", "path": "closing-stock" },
  { "name": "Non Saleable To Saleable", "path": "non-saleable-to-saleable" },
  { "name": "Saleable To Non Saleable", "path": "saleable-to-non-saleable" },
  // SalesReport
  { "name": "Sale Register", "path": "sale-register" },
  { "name": "Day Wise Sale Register", "path": "day-wise-sale-register" },
  { "name": "Monthly Sale Register", "path": "monthly-sale-register" },
  { "name": "Item Wise Sale Report", "path": "item-wise-sale-report" },
  { "name": "Bill Item Wise Sale Register", "path": "bill-item-wise-sale-register" },
  { "name": "Company Wise Salt Wise Sale Summary", "path": "company-wise-salt-wise-sale-summary" },
  { "name": "Party Wise Sale Summary", "path": "party-wise-sale-statment" },
  { "name": "Party Wise Sale Report", "path": "party-wise-sale-report" },
  { "name": "Category Wise Item Wise Sale Summary", "path": "category-wise-item-wise-sale-summary" },
  { "name": "Category Wise Sale Summary", "path": "category-wise-sale-summary" },
  { "name": "Clubbed Sale Register ", "path": "clubbed-sale-register" },
  { "name": "Company Wise Item Wise Sale Summary", "path": "company-wise-item-wise-sale-summary" },
  { "name": "Company Wise Party Wise Sale Summary", "path": "company-wise-party-wise-sale-summary" },
  { "name": "Company Wise Group Wise Sale Summary", "path": "company-wise-group-wise-sale-summary" },
  { "name": "Company Wise Sale Summary", "path": "company-wise-sale-summary" },
  { "name": "Disc Wise Sale Summary", "path": "disc-wise-sale-summary" },
  { "name": "Group SubGroup Month Wise Sale Report", "path": "group-subGroup-month-wise-sale-report" },
  { "name": "Group Wise Item Wise Sale Summary", "path": "group-wise-item-wise-sale-summary" },
  { "name": "Group Wise Sale Summary", "path": "group-wise-sale-summary" },
  { "name": "Item Moving Report", "path": "item-moving-report" },
  { "name": "Item Party Sale Report", "path": "item-party-sale-report" },
  { "name": "Item Wise Batch Wise Tran Ledger", "path": "item-wise-batch-wise-tranLedger" },
  { "name": "Item Wise Sale Summary", "path": "item-wise-sale-summary" },
  { "name": "Mfg Company Wise Bill Wise Sale Register", "path": "MfgCompany-wise-bill-wise-sale-register" },
  { "name": "Mfg Company Wise Item Wise Sale Register", "path": "MfgCompany-wise-item-wise-sale-register" },
  { "name": "Mobile Wise Sale Register", "path": "mobile-wise-sale-register" },
  { "name": "MR Wise Item Wise Sale Summary", "path": "MRWise-item-wise-sale-summary" },
  { "name": "Mr Wise Sale Summary", "path": "MrWise-sale-summary" },
  { "name": "Party Wise Comapny Wise Sale Summary", "path": "party-wise-comapny-wise-sale-summary" },
  { "name": "Party Wise Group Wise Sale Summary", "path": "party-wise-group-wise-sale-summary" },
  { "name": "Party Wise Item Wise Sale Summary", "path": "party-wise-item-wise-sale-summary" },
  { "name": "Party Wise Salt Wise Sale Summary", "path": "party-wise-salt-wise-sale-summary" },
  { "name": "Price Diff Credit Note", "path": "price-diff-credit-note" },
  { "name": "Salt Wise Item Wise Sale Summary", "path": "salt-wise-item-wise-sale-summary" },
  { "name": "Salt Wise Sale Summary", "path": "salt-wise-sale-summary" },
  { "name": "Supplier Wise Item Wise Sale Register", "path": "supplier-wise-item-wise-sale-register" },
  // Purchase Report
  { "name": "Purchase Register", "path": "purchase-register" },
  { "name": "Mrp Rate Diff Report", "path": "mrpRate-diff-report" },
  { "name": "Supplier Purchase Register", "path": "supplier-purchase-register" },
  { "name": "Item Wise Best Supplier", "path": "itemWise-best-supplier" },
  { "name": "Group Monthly Purchase", "path": "group-monthly-purchase" },
  { "name": "Party Purchase Report", "path": "party-purchase-report" },
  { "name": "Monthly Purchase", "path": "monthly-purchase" },
  { "name": "DayWise Purchase", "path": "dayWise-purchase" },
  { "name": "Items Purchase Report", "path": "item-purchase-report" },
  { "name": "Bill Wise Item Purchase", "path": "bill-wise-item-purchase" },
  // GSTReport
  { "name": "GST Returns", "path": "gst-return" },
  { "name": "GST Column Purchase", "path": "gst-column-purchase" },
  { "name": "GST Column Purchase Old", "path": "gst-column-purchase-old" },
  { "name": "GST Column Sale", "path": "'gst-column-sale" },
  { "name": "GST Column Sale Old", "path": "'gst-column-sale-old" },
  { "name": "GST Purchase Register", "path": "gst-purchase-register" },
  { "name": "GST Registers", "path": "gst-registers" },
  { "name": "GST Sale Register", "path": "gst-sale-register" },
  { "name": "GST Tax Clubbing", "path": "gst-tax-clubbing" },
  { "name": "Show GST Detail", "path": "show-gst-detail" },
  { "name": "Update GST IN PinCode", "path": "update-gstin-pin-code" },
  { "name": "E-Way E-Invoice", "path": "eway-invoice" },
  { "name": "TCS TDS Registes", "path": "tcstds-register" },
  // DepartmentalReport
  { "name": "Gp Report Grid", "path": "GpReportGrid" },
  { "name": "Bill Wise Item Wise Schedule Register Retail", "path": "billWise-itemWise-schedule-register-retail" },
  { "name": "Bill Wise Item Wise Schedule Register Whole Sale", "path": "billWise-itemWise-schedule-register-wholsale" },
  // DispatchModule
  { "name": "Annexure", "path": "annexure" },
  { "name": "Checking", "path": "checking" },
  { "name": "Delivery", "path": "delivery" },
  { "name": "Dispatch DashBoard", "path": "dispatch-dash-board" },
  { "name": "Dispatch Report", "path": "dispatch-report" },
  { "name": "Packing", "path": "packing" },
  { "name": "Picking Dispatch Summary", "path": "picking-dispatch-summary" },
  { "name": "Un Deliver", "path": "un-deliver" },
  { "name": "Update Stock Value", "path": "update-stock-value" },
  // Email
  { "name": "Mail Config Entry", "path": "mail-config-entry" },
  { "name": "General Email", "path": "general-email" },
  { "name": "General SMS", "path": "general-SMS" },
  // Exit
  { "name": "Set Device", "path": "set-device" },
  { "name": "Refresh Printer Names", "path": "refresh-printer-names" },
  { "name": "Menu Help", "path": "MenuHelp" },
  { "name": "Change Wallpaper", "path": "change-wallpaper" },

]

export default SearcBarData;